### ISSUE TITLE
Error Converting string to GUID in CancelOrderbyID

### ISSUE THREAD

**Issue by geniosoft** [dougdellolio/coinbasepro-csharp#210]
Hello,

in the software i am developing i monitor price and when it lowers more then a percentage i cancel one buy order and create another one.

I register guid string and use it to cancel order.

My code (VB.NET) is as follows:

Dim r1 As CoinbasePro.Services.Orders.Models.Responses.CancelOrderResponse
r1 = Await clientcb.OrdersService.CancelOrderByIdAsync(m_ordercode)

m_ordercode contains "6ebd5c18-f661-4cc0-9fbf-35087598b2b7"

but i catch this error:

Newtonsoft.Json.JsonSerializationException: 'Error converting value "6ebd5c18-f661-4cc0-9fbf-35087598b2b7" to type 'System.Collections.Generic.IEnumerable`1[System.Guid]'. Path '', line 1, position 38.'

Inner Exception:
ArgumentException: Could not cast or convert from System.String to System.Collections.Generic.IEnumerable`1[System.Guid].

Can you help to correct my code or detecting where the bug is?

Thank you very much,
Fernando Pinheiro

**Comment by dougdellolio** [comment]
@geniosoft you found a bug in the client. perhaps the json response was changed at some point but the response included one Guid for the cancelled order however we were expecting a list of them. Either way it should now be fixed with https://github.com/dougdellolio/coinbasepro-csharp/pull/211. Let me know if you are still having issues.

thanks!

**Comment by geniosoft** [comment]
Thank you for the detection and correction, but i still don't know how to use it, as the latest nuget package i can use is version 1.03 from August 22.

I tried downloading the actual zipped project from github and inserting it on my solution, but it didn't recognized the namespace and i got back to nuget with bugged version.

**Comment by dougdellolio** [comment]
@geniosoft I just released the latest version to NuGet (v1.0.31). Please upgrade and it should work now.

**Comment by geniosoft** [comment]
Thank you. I testest it and it now works.
